apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-web-content
  namespace: argocdnew
data:
  index.html: |
    <h1>Hello from Devyansh ðŸš€</h1>
    <p>This page is deployed using ArgoCD (GitOps) âœ…</p>

